name: etlbuild

on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -
        name: Check latestver
        id: lv
        run: ./latestver.sh
      - 
        name: Set tag var
        id: vars
        run: echo ::set-output name=version::$(./latestver.sh)
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Quay Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          push: true
          context: .
          file: Dockerfile
          tags: |
            quay.io/cowbay/helium-etl:latest
            quay.io/cowbay/helium-etl:${{ steps.vars.output.version }}
            quay.io/cowbay/helium-etl:${{ github.sha }}
